# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://Philescandon.github.io/cs677wk1/"

git_url = "https://github.com/Philescandon/cs677wk1/tree/{branch}/"

def custom_doc_links(name): return None
